version: '3.8'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=scheduler_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: /Users/bunmialao/Documents/scheduler
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=scheduler_db
      - DB_PORT=3306
    stdin_open: true
    tty: true
volumes: 
  db: